const fs = require('fs');
let content = fs.readFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', 'utf8');
let evalContent = content.replace('const cbseData =', 'global.cbseData =');
eval(evalContent);

const ch5 = [
    {"question": "Qutb Minar was built by:", "options": ["Qutbuddin Aybak and Iltutmish", "Akbar and Jahangir", "Babar", "Alauddin Khalji"], "answer": 0, "explanation": "Qutbuddin Aybak had this monument constructed around 1199... The rest was completed by Iltutmish around 1229."},
    {"question": "During the Middle Ages, what were the two kinds of structures built by kings?", "options": ["Forts/palaces and structures meant for public activity (temples, mosques, etc.)", "Schools and hospitals", "Railways and airports", "Offices and factories"], "answer": 0, "explanation": "Between the eighth and the eighteenth centuries kings and their officers built two kinds of structures: the first were forts, palaces, garden residences... second were structures meant for public activity including temples, mosques, tanks..."},
    {"question": "What architectural style is called 'trabeate' or 'corbelled'?", "options": ["Placing a horizontal beam across two vertical columns", "Building huge domes over arches", "Using steel rebars", "Making pointed roofs with tiles"], "answer": 0, "explanation": "Between the seventh and tenth centuries architects started adding more rooms, doors and windows to buildings. Roofs, doors and windows were still made by placing a horizontal beam across two vertical columns, a style of architecture called 'trabeate' or 'corbelled'."},
    {"question": "The Kandariya Mahadeva temple dedicated to Shiva was constructed in 999 by:", "options": ["King Dhangadeva of the Chandela dynasty", "King Rajaraja Chola", "Ruler of the Rashtrakuta dynasty", "The Pallavas"], "answer": 0, "explanation": "The Kandariya Mahadeva temple dedicated to Shiva was constructed in 999 by the king Dhangadeva of the Chandela dynasty."},
    {"question": "What was the 'shikhara' of a temple?", "options": ["The main hall", "The highest roof/tower above the main shrine", "The entrance gateway", "The place for ritual dances"], "answer": 1, "explanation": "The main shrine is generally located directly under the tallest tower, called the shikhara."},
    {"question": "The Rajarajeshvara temple was built in:", "options": ["Thanjavur", "Kanchipuram", "Madurai", "Delhi"], "answer": 0, "explanation": "The Rajarajeshvara temple at Thanjavur had the tallest shikhara amongst temples of its time."},
    {"question": "How did they build the tall shikhara of the Rajarajeshvara temple?", "options": ["They built an inclined path to the top so elephants could pull the stone", "They used modern cranes", "They carved it from top to bottom from a single rock", "They used wooden scaffolding that could bear any weight"], "answer": 0, "explanation": "There were no cranes in those days and the 90 tonne stone for the top of the shikhara was too heavy to lift manually. So the architects built an inclined path to the top of the temple..."},
    {"question": "From the twelfth century, what architectural innovation gave rise to the 'arcuate' style?", "options": ["The use of true arches where the keystone transferred the weight", "The use of long wooden beams", "Building flat roofs out of concrete", "Using paper mache"], "answer": 0, "explanation": "The weight of the superstructure above the doors and windows was sometimes carried by arches. This architectural form was called 'arcuate'."},
    {"question": "In construction, what material started being used increasingly from the twelfth century because it was high-quality and hardened into fast-setting concrete?", "options": ["Limestone cement", "Mud", "Tar", "Bronze"], "answer": 0, "explanation": "Limestone cement was increasingly used in construction. This was very high-quality cement, which, when mixed with stone chips hardened into concrete."},
    {"question": "Muslim Sultans did not claim to be incarnations of God but Persian court chronicles described the Sultan as:", "options": ["The Shadow of God", "The brother of God", "Equal to God", "A temple priest"], "answer": 0, "explanation": "Muslim Sultans and Padshahs did not claim to be incarnations of God but Persian court chronicles described the Sultan as the 'Shadow of God'."},
    {"question": "Which Sultan won universal respect for constructing a large reservoir just outside Dehli-i-Kuhna called Hauz-i-Sultani?", "options": ["Iltutmish", "Balban", "Alauddin Khalji", "Qutbuddin Aybak"], "answer": 0, "explanation": "Sultan Iltutmish won universal respect for constructing a large reservoir just outside Dehli-i-Kuhna. It was called the Hauz-i-Sultani or the 'King's Reservoir'."},
    {"question": "Why did temples become targets of attack when kings attacked one another's kingdoms?", "options": ["Because kings built temples to demonstrate their devotion to God and their power and wealth", "Because temples were the only places with food", "Because kings did not like religion", "To stop priests from ruling"], "answer": 0, "explanation": "Because kings built temples to demonstrate their devotion to God and their power and wealth, it is not surprising that when they attacked one another's kingdoms they often targeted these buildings."},
    {"question": "Which king invaded Sri Lanka and took away the statue of the Buddha made entirely of gold?", "options": ["Pandyan king Shrimara Shrivallabha", "Chola king Rajendra I", "Sultan Mahmud of Ghazni", "Dantidurga"], "answer": 0, "explanation": "In the early ninth century when the Pandyan king Shrimara Shrivallabha invaded Sri Lanka and defeated the king... He removed all the valuables... The statue of the Buddha made entirely of gold in the Jewel Palace..."},
    {"question": "When the Chola king Rajendra I built a Shiva temple in his capital, he filled it with:", "options": ["Prized statues seized from defeated rulers", "Grains", "Wooden toys", "Only silver coins"], "answer": 0, "explanation": "In the early eleventh century, when the Chola king Rajendra I built a Shiva temple in his capital he filled it with prized statues seized from defeated rulers."},
    {"question": "Babur laid out formal gardens placed within rectangular walled enclosures and divided into four quarters, which were called:", "options": ["Chahar bagh", "Bagh-e-Eram", "Jannat", "Bagh-i-Fiza"], "answer": 0, "explanation": "These gardens were called chahar bagh, four gardens, because of their symmetrical division into quarters."},
    {"question": "The central towering dome and the tall gateway (pishtaq) became important aspects of Mughal architecture, first visible in:", "options": ["Humayun's tomb", "The Taj Mahal", "Panch Mahal", "Qutb Minar"], "answer": 0, "explanation": "The central towering dome and the tall gateway (pishtaq) became important aspects of Mughal architecture, first visible in Humayun's tomb."},
    {"question": "The tradition of 'eight paradises' or hasht bihisht in Mughal architecture means:", "options": ["A central hall surrounded by eight rooms", "Eight separate gardens", "A building with eight domes", "Eight doors on each side"], "answer": 0, "explanation": "The tomb was placed in the centre of a huge formal chahar bagh and built in the tradition known as 'eight paradises' or hasht bihisht - a central hall surrounded by eight rooms."},
    {"question": "During Shah Jahan's reign, the diwan-i khas o aam (public and private audience halls) were also described as 'chihil sutun' meaning:", "options": ["Forty-pillared halls", "Forty-doored halls", "Forty-windowed halls", "Forty-domed halls"], "answer": 0, "explanation": "These courts were also described as chihil sutun or forty-pillared halls, placed within a large courtyard."},
    {"question": "Shah Jahan's audience hall was specially constructed to resemble a:", "options": ["Mosque", "Church", "Market", "Temple"], "answer": 0, "explanation": "Shah Jahan's audience halls were specially constructed to resemble a mosque. The pedestal on which his throne was placed was frequently described as the qibla, the direction faced by Muslims at prayer."},
    {"question": "What is 'pietra dura'?", "options": ["Coloured, hard stones placed in depressions carved into marble or sandstone creating beautiful, ornate patterns", "A type of pillar", "A method of painting", "A water fountain technique"], "answer": 0, "explanation": "Behind the emperor's throne were a series of pietra dura inlays... Pietra dura are coloured, hard stones placed in depressions carved into marble or sandstone creating beautiful, ornate patterns."},
    {"question": "The Taj Mahal was constructed in:", "options": ["Agra", "Delhi", "Lahore", "Kabul"], "answer": 0, "explanation": "The architectural majesty of Shah Jahan's reign was best adapted in the river-front garden in the layout of the Taj Mahal at Agra."},
    {"question": "In Shahjahanabad, Shah Jahan's new city in Delhi, who was allowed access to the Yamuna river-front?", "options": ["Only specially favoured nobles, like his eldest son Dara Shukoh", "All citizens", "Ordinary merchants", "The army only"], "answer": 0, "explanation": "Only specially favoured nobles - like his eldest son Dara Shukoh - were given access to the river. All others had to construct their homes in the city away from the River Yamuna."},
    {"question": "What was the 'Bangla dome' that the Mughals adapted in their architecture?", "options": ["A roof designed to resemble a thatched hut", "A dome made of glass", "A dome with a hole in the center", "A square-shaped dome"], "answer": 0, "explanation": "In Bengal, for example, the local rulers had developed a roof that was designed to resemble a thatched hut. The Mughals liked this 'Bangla dome' so much that they used it in their architecture."},
    {"question": "Which temples in Vrindavan, near Mathura, were constructed in architectural styles very similar to the Mughal palaces in Fatehpur Sikri?", "options": ["Govind Deva temple", "Kandariya Mahadeva temple", "Rajarajeshvara temple", "Jagannath temple"], "answer": 0, "explanation": "Temples in Vrindavan, near Mathura, were constructed in architectural styles that were very similar to the Mughal palaces in Fatehpur Sikri (like the temple of Govind Deva)."},
    {"question": "In Fatehpur Sikri, many of the buildings show the influence of the architectural styles of:", "options": ["Gujarat and Malwa", "Kashmir and Punjab", "Bengal and Assam", "Kerala and Tamil Nadu"], "answer": 0, "explanation": "In Akbar's capital at Fatehpur Sikri many of the buildings show the influence of the architectural styles of Gujarat and Malwa."}
];

const ch6 = [
    {"question": "Thanjavur, the capital of the Cholas, was primarily what type of town?", "options": ["A temple town and administrative center", "Only a port town", "A garrison town", "A weavers' town"], "answer": 0, "explanation": "Thanjavur, the capital of the Cholas, as it was a thousand years ago, was a temple town and an administrative centre."},
    {"question": "The Rajarajeshvara temple in Thanjavur was designed by the architect:", "options": ["Kunjamallan Rajaraja Perunthachchan", "Amir Khusrau", "Abul Fazl", "Ustad Ahmad Lahauri"], "answer": 0, "explanation": "The townspeople are all praise for its architect Kunjaramallan Rajaraja Perunthachchan who has proudly carved his name on the temple wall."},
    {"question": "What was generated in the mandapas (pavilions) of the temple?", "options": ["The king held court here and issued orders to subordinates", "Cotton was weaved", "Iron was melted", "Ships were built"], "answer": 0, "explanation": "Kings hold court in these mandapas, issuing orders to their subordinates."},
    {"question": "What did the Saliya weavers of Thanjavur produce?", "options": ["Cloth for flags to be used in the temple festival, fine cottons for the king and nobility", "Silk only", "Woolen carpets", "Leather goods"], "answer": 0, "explanation": "The Saliya weavers of Thanjavur and the adjoining town of Uraiyur are busy producing cloth for flags to be used in the temple festival, fine cottons for the king and nobility and coarse cotton for the masses."},
    {"question": "At Svamimalai, the sthapatis or sculptors were making:", "options": ["Exquisite bronze idols and tall, ornamental bell metal lamps", "Wooden chariots", "Stone pillars", "Gold jewelry"], "answer": 0, "explanation": "Some distance away at Svamimalai, the sthapatis or sculptors are making exquisite bronze idols and tall, ornamental bell metal lamps."},
    {"question": "Bell metal contains a greater proportion of which metal than other kinds of bronze?", "options": ["Tin", "Copper", "Iron", "Zinc"], "answer": 0, "explanation": "Bronze is an alloy containing copper and tin. Bell metal produces a bell-like sound because it contains a greater proportion of tin than other kinds of bronze."},
    {"question": "Chola bronze statues were made using the:", "options": ["'Lost wax' technique", "Carving method", "Stamping method", "Stone moulding technique"], "answer": 0, "explanation": "Chola bronze statues were made using the 'lost wax' technique. First, an image was made of wax. This was covered with clay and allowed to dry. Next it was heated, and a tiny hole was made in the clay cover. The molten wax was drained out through this hole."},
    {"question": "Which town in Madhya Pradesh was celebrated for its temple to Bhillasvamin?", "options": ["Bhilsa or Vidisha", "Sanchi", "Mandu", "Gwalior"], "answer": 0, "explanation": "Temple towns represent a very important pattern of urbanisation... Important temple towns included Bhillasvamin (Bhilsa or Vidisha in Madhya Pradesh)."},
    {"question": "Ajmer (Rajasthan) was the capital of the Chauhan kings and later became the suba headquarters under the Mughals. It is associated with which celebrated Sufi saint?", "options": ["Khwaja Muinuddin Chishti", "Nizamuddin Auliya", "Baba Farid", "Salim Chishti"], "answer": 0, "explanation": "Ajmer is associated with the celebrated Sufi saint, Khwaja Muinuddin Chishti (twelfth century) who attracted devotees from all creeds."},
    {"question": "Near Ajmer is a lake which has attracted pilgrims from ancient times. What is it called?", "options": ["Pushkar", "Sambhar", "Chilika", "Dal"], "answer": 0, "explanation": "Pushkar lake near Ajmer has attracted pilgrims from ancient times."},
    {"question": "What was the 'mandapika' in a small town?", "options": ["A mandi or market where nearby villagers brought their produce to sell", "A temple chariot", "A fort gate", "An administrative office"], "answer": 0, "explanation": "They usually had a mandapika (or mandi of later times) to which nearby villagers brought their produce to sell."},
    {"question": "Market streets lined with shops were called:", "options": ["Hatta (haat of later times)", "Bazaar", "Chor bazaar", "Ganj"], "answer": 0, "explanation": "They also had market streets called hatta (haat of later times) lined with shops."},
    {"question": "Often, a samanta or a zamindar built a fortified palace in or near these towns. What was one of their powers regarding trade?", "options": ["They levied taxes on traders, artisans and articles of trade", "They banned all trade", "They fixed standard weights for the whole empire", "They built all the ships"], "answer": 0, "explanation": "Usually a samanta or, in later times, a zamindar built a fortified palace in or near these towns. They levied taxes on traders, artisans and articles of trade..."},
    {"question": "Which nomad traders brought their families and travelled in caravans called 'Tanda'?", "options": ["Banjara", "Marwari", "Chettiar", "Khatri"], "answer": 0, "explanation": "There were many kinds of traders. These included the Banjaras... who moved in caravans called tanda."},
    {"question": "Which guilds were the most famous among the trading guilds of south India from the eighth century onwards?", "options": ["Manigramam and Nanadesi", "Khatris and Oswals", "Chettiars and Baniyas", "Panchalas and Vishwakarma"], "answer": 0, "explanation": "There were several such guilds in south India from the eighth century onwards - the most famous being the Manigramam and Nanadesi. These guilds traded extensively both within the peninsula and with Southeast Asia and China."},
    {"question": "Which community traded primarily with the ports of the Red Sea, Persian Gulf, East Africa, Southeast Asia and China?", "options": ["Arab, Persian, Chinese, Jewish and Syrian Christian traders", "Only the Portuguese", "Only English companies", "Only Marwari Oswal"], "answer": 0, "explanation": "The towns on the west coast were home to Arab, Persian, Chinese, Jewish and Syrian Christian traders."},
    {"question": "Indian spices and cloth sold in the Red Sea ports were purchased by:", "options": ["Italian traders", "Russian traders", "Greek traders", "Spanish traders"], "answer": 0, "explanation": "Indian spices and cloth sold in the Red Sea ports were purchased by Italian traders and eventually reached European markets, fetching very high profits."},
    {"question": "The spice trade (especially pepper, cinnamon, nutmeg, dried ginger) became an important part of:", "options": ["European cooking", "Asian cooking", "African cooking", "Australian cooking"], "answer": 0, "explanation": "Spices grown in tropical climates (pepper, cinnamon, nutmeg, dried ginger, etc.) became an important part of European cooking."},
    {"question": "Which craftspersons were famous for their inlay work in copper and silver, which came to be called Bidri?", "options": ["The craftspersons of Bidar", "The weavers of Surat", "The sculptors of Thanjavur", "The shipbuilders of Masulipatnam"], "answer": 0, "explanation": "The craftspersons of Bidar were so famed for their inlay work in copper and silver that it came to be called Bidri."},
    {"question": "The Panchalas or Vishwakarma community consisted of:", "options": ["Goldsmiths, bronzesmiths, blacksmiths, masons and carpenters", "Only weavers", "Only farmers", "Only priests"], "answer": 0, "explanation": "The Panchalas or Vishwakarma community, consisting of goldsmiths, bronzesmiths, blacksmiths, masons and carpenters, were essential to the building of temples."},
    {"question": "Which city was the capital of the Vijayanagara Empire?", "options": ["Hampi", "Surat", "Masulipatnam", "Bidar"], "answer": 0, "explanation": "Hampi is located in the Krishna-Tungabhadra basin, which formed the nucleus of the Vijayanagara Empire, founded in 1336."},
    {"question": "Hampi's architecture was distinctive. What did its buildings have?", "options": ["Splendid arches, domes and pillared halls with niches for holding sculptures", "Flat roofs covered in grass", "Only wooden structures without any stone", "Structures completely made of mud"], "answer": 0, "explanation": "The architecture of Hampi was distinctive. The buildings in the royal complex had splendid arches, domes and pillared halls with niches for holding sculptures."},
    {"question": "In the fifteenth and sixteenth centuries, Hampi bustled with commercial and cultural activities. Which trading communities controlled its markets?", "options": ["Moors (Muslim merchants), Chettis and agents of European traders like the Portuguese", "Only local street vendors", "Chinese traders", "Russian spies"], "answer": 0, "explanation": "Hampi bustled with commercial and cultural activities. Moors (a name used collectively for Muslim merchants), Chettis and agents of European traders such as the Portuguese, thronged the markets of Hampi."},
    {"question": "Which city in Gujarat was the emporium of western trade during the Mughal period?", "options": ["Surat", "Ahmedabad", "Broach", "Khambhat"], "answer": 0, "explanation": "Surat in Gujarat was the emporium of western trade during the Mughal period. Surat was the gateway for trade with West Asia via the Gulf of Ormuz."},
    {"question": "Surat has also been called the gate to:", "options": ["Mecca, because many pilgrim ships set sail from here", "Delhi", "Asia", "Europe"], "answer": 0, "explanation": "Surat has also been called the gate to Mecca because many pilgrim ships set sail from here."}
];

global.cbseData["7"].history.mcqs.ch5 = ch5;
global.cbseData["7"].history.mcqs.ch6 = ch6;

let finalContent = 'const cbseData = ' + JSON.stringify(global.cbseData, null, 4) + ';\n';
fs.writeFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', finalContent);
console.log('Class 7 History Ch5 & Ch6 added.');
