const fs = require('fs');
let content = fs.readFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', 'utf8');
let evalContent = content.replace('const cbseData =', 'global.cbseData =');
eval(evalContent);

const ch7 = [
    {"question": "Many societies in the subcontinent did not follow the social rules and rituals prescribed by the Brahmanas. Such societies are often called:", "options": ["Tribes", "Empires", "Guilds", "Mandalas"], "answer": 0, "explanation": "Many societies in the subcontinent did not follow the social rules and rituals prescribed by the Brahmanas... Such societies are often called tribes."},
    {"question": "Tribal people were found in almost every region of the subcontinent. The area and influence of a tribe:", "options": ["Remained the same", "Varied at different points of time", "Was restricted to the south", "Was usually very small"], "answer": 1, "explanation": "Tribal people were found in almost every region of the subcontinent. The area and influence of a tribe varied at different points of time."},
    {"question": "The Khokhar tribe was very influential during the thirteenth and fourteenth centuries in:", "options": ["Punjab", "Bengal", "Odisha", "Maharashtra"], "answer": 0, "explanation": "In Punjab, the Khokhar tribe was very influential during the thirteenth and fourteenth centuries."},
    {"question": "Who was Kamal Khan Gakkhar?", "options": ["A chief of the Gakkhar tribe, made a noble (mansabdar) by Emperor Akbar", "A Mughal general", "A weaver from Surat", "A Rajput king"], "answer": 0, "explanation": "Later, the Gakkhars became more important. Their chief, Kamal Khan Gakkhar, was made a noble (mansabdar) by Emperor Akbar."},
    {"question": "Which tribe was dominant in the north-west before the Mughals?", "options": ["Balochis", "Gonds", "Ahoms", "Cheras"], "answer": 0, "explanation": "In Multan and Sind, the Langahs and Arghuns dominated... The Balochis were another large and powerful tribe in the north-west."},
    {"question": "The Balochis were divided into many smaller:", "options": ["Clans under different chiefs", "Empires", "Guilds", "Temples"], "answer": 0, "explanation": "The Balochis were divided into many smaller clans under different chiefs."},
    {"question": "In the western Himalaya lived the shepherd tribe of:", "options": ["Gaddis", "Ahoms", "Bhils", "Gonds"], "answer": 0, "explanation": "In the western Himalaya lived the shepherd tribe of Gaddis."},
    {"question": "Chera chiefdoms had emerged in the present-day Bihar and Jharkhand by the:", "options": ["Twelfth century", "Fifth century", "Second century BCE", "Eighteenth century"], "answer": 0, "explanation": "In many areas of present-day Bihar and Jharkhand, Chera chiefdoms had emerged by the twelfth century."},
    {"question": "Who defeated the Cheras in 1591?", "options": ["Raja Man Singh, Akbar's famous general", "Babur", "Iltutmish", "Ashoka"], "answer": 0, "explanation": "Raja Man Singh, Akbar's famous general, attacked and defeated the Cheras in 1591."},
    {"question": "Which tribe was spread across western and central India?", "options": ["Bhils", "Gakkhars", "Nagas", "Ahoms"], "answer": 0, "explanation": "The Maharashtra highlands and Karnataka were home to Kolis, Berads and numerous others... Further south there were large tribal populations of Koragas, Vetars, Maravars and many others. The large tribe of Bhils was spread across western and central India."},
    {"question": "The Banjaras were the most important:", "options": ["Trader-nomads", "Soldiers", "Weavers", "Farmers"], "answer": 0, "explanation": "The Banjaras were the most important trader-nomads. Their caravan was called tanda."},
    {"question": "Which Sultan used the Banjaras to transport grain to the city markets?", "options": ["Alauddin Khalji", "Balban", "Iltutmish", "Qutbuddin Aybak"], "answer": 0, "explanation": "Sultan Alauddin Khalji used the Banjaras to transport grain to the city markets."},
    {"question": "Nomadic pastoralists moved over long distances with their animals. They lived on:", "options": ["Milk and other pastoral products", "Only agriculture", "Hunting only", "Begging"], "answer": 0, "explanation": "Nomadic pastoralists moved over long distances with their animals. They lived on milk and other pastoral products."},
    {"question": "What did nomadic pastoralists commonly exchange with settled agriculturists?", "options": ["They exchanged wool, ghee, etc., for grain, cloth, utensils and other products", "They gave gold for silver", "They gave weapons for shelter", "They traded silk for tea"], "answer": 0, "explanation": "They also exchanged wool, ghee, etc., with settled agriculturists for grain, cloth, utensils and other products."},
    {"question": "Many pastoral tribes reared and sold:", "options": ["Animals, such as cattle and horses, to the prosperous people", "Elephants", "Fish", "Dogs"], "answer": 0, "explanation": "Many pastoral tribes reared and sold animals, such as cattle and horses, to the prosperous people."},
    {"question": "Different castes of petty pedlars travelled from village to village making and selling wares such as:", "options": ["Ropes, reeds, straw matting and coarse sacks", "Gold coins", "Iron swords", "Silk sarees"], "answer": 0, "explanation": "Different castes of petty pedlars travelled from village to village. They made and sold wares such as ropes, reeds, straw matting and coarse sacks."},
    {"question": "As the economy and the needs of society grew, new castes emerged within the varnas. These smaller castes were called:", "options": ["Jatis", "Kulas", "Samantas", "Subas"], "answer": 0, "explanation": "Smaller castes, or jatis, emerged within the varnas... For example, new castes appeared amongst the Brahmanas..."},
    {"question": "Among the Kshatriyas, new lineages became powerful by the eleventh and twelfth centuries. They belonged to different lineages such as Hunas, Chandelas, Chalukyas and others, and were collectively called:", "options": ["Rajputs", "Gonds", "Ahoms", "Banjaras"], "answer": 0, "explanation": "Among the Kshatriyas, new Rajput clans became powerful by the eleventh and twelfth centuries... Many of these clans came to be regarded as Rajputs."},
    {"question": "The rise of Rajput clans to the position of rulers set an example for the:", "options": ["Tribal people to follow", "Brahmanas", "European traders", "Persian historians"], "answer": 0, "explanation": "The rise of Rajput clans to the position of rulers set an example for the tribal people to follow."},
    {"question": "Where did the Gonds live?", "options": ["In a vast forested region called Gondwana", "In the Thar Desert", "In the Himalayas", "Along the Malabar and Coromandel coasts"], "answer": 0, "explanation": "The Gonds lived in a vast forested region called Gondwana – or “country inhabited by Gonds”."},
    {"question": "What kind of agriculture did the Gonds practice?", "options": ["Shifting cultivation", "Terrace farming", "Hydroponics", "Plantation farming"], "answer": 0, "explanation": "They practiced shifting cultivation."},
    {"question": "When the Delhi Sultanate was declining, a few large Gond kingdoms began to:", "options": ["Dominate the smaller Gond chiefs", "Merge with the Mughals", "Move to the north-east", "Adopt Buddhism"], "answer": 0, "explanation": "At a time when the power of the Delhi Sultans was declining, a few large Gond kingdoms began to dominate the smaller Gond chiefs."},
    {"question": "The Gond kingdom of Garha Katanga is mentioned in which book?", "options": ["Akbar Nama", "Babur Nama", "Ain-i-Akbari", "Kitab-ul-Hind"], "answer": 0, "explanation": "The Akbar Nama, a history of Akbar's reign, mentions the Gond kingdom of Garha Katanga that had 70,000 villages."},
    {"question": "In the Gond administration, the kingdom was divided into 'garhs', which were further divided into units of 84 villages called:", "options": ["Chaurasi", "Pargana", "Barhot", "Mandal"], "answer": 0, "explanation": "Each garh was controlled by a particular Gond clan. This was further divided into units of 84 villages called chaurasi."},
    {"question": "The Ahoms migrated to the Brahmaputra valley from present-day Myanmar in the:", "options": ["Thirteenth century", "Eleventh century", "Fifteenth century", "Seventeenth century"], "answer": 0, "explanation": "The Ahoms migrated to the Brahmaputra valley from present-day Myanmar in the thirteenth century."}
];

const ch8 = [
    {"question": "Before large kingdoms emerged, what did different groups of people worship?", "options": ["Their own gods and goddesses", "Only one universal God", "No gods at all", "Only the sun and the moon"], "answer": 0, "explanation": "Before large kingdoms emerged, different groups of people worshipped their own gods and goddesses."},
    {"question": "As towns, trade, and empires grew, what new idea about life and rebirth became widely accepted?", "options": ["The idea that all living things pass through countless cycles of birth and rebirth performing good deeds and bad", "The idea that there is only one life", "The idea that rebirth only happens for kings", "The idea that animals do not have souls"], "answer": 0, "explanation": "The idea that all living things pass through countless cycles of birth and rebirth performing good deeds and bad came to be widely accepted."},
    {"question": "What other idea about social privileges became a subject of debate?", "options": ["The belief that social privileges came from birth in a 'noble' family or a 'high' caste", "The idea that everyone is born equal", "The idea that women are superior to men", "The belief that wealth ensures salvation"], "answer": 0, "explanation": "Similarly, the idea that all human beings are not equal even at birth gained ground during this period. The belief that social privileges came from birth in a 'noble' family or a 'high' caste was the subject of many learned texts."},
    {"question": "How could the cycle of rebirth be broken according to the teachings of the Buddha and the Jainas?", "options": ["Through personal effort", "By paying the priests", "By sacrificing animals", "By building large temples"], "answer": 0, "explanation": "Many people were uneasy with such ideas and turned to the teachings of the Buddha or the Jainas according to which it was possible to overcome social differences and break the cycle of rebirth through personal effort."},
    {"question": "Others felt attracted to the idea of a Supreme God who could deliver humans from such bondage if approached with devotion. This idea was advocated in the:", "options": ["Bhagavadgita", "Rigveda", "Koran", "Zend Avesta"], "answer": 0, "explanation": "Others felt attracted to the idea of a Supreme God who could deliver humans from such bondage if approached with devotion (or bhakti). This idea, advocated in the Bhagavadgita, grew in popularity..."},
    {"question": "Which supreme deities came to be worshipped through elaborate rituals?", "options": ["Shiva, Vishnu and Durga", "Only Brahma", "Indra and Agni", "Varuna and Vayu"], "answer": 0, "explanation": "Shiva, Vishnu and Durga as supreme deities came to be worshipped through elaborate rituals."},
    {"question": "The seventh to ninth centuries saw the emergence of new religious movements in South India led by:", "options": ["Nayanars (saints devoted to Shiva) and Alvars (saints devoted to Vishnu)", "Buddhists and Jainas", "Sufis and Bhaktas", "Gonds and Ahoms"], "answer": 0, "explanation": "The seventh to ninth centuries saw the emergence of new religious movements, led by the Nayanars (saints devoted to Shiva) and Alvars (saints devoted to Vishnu)."},
    {"question": "The Nayanars and Alvars came from all castes, including those considered 'untouchable' like the:", "options": ["Pulaiyar and the Panars", "Brahmanas", "Rajputs", "Kayasthas"], "answer": 0, "explanation": "They came from all castes including those considered 'untouchable' like the Pulaiyar and the Panars."},
    {"question": "The Nayanars and Alvars drew upon the ideals of love and heroism found in:", "options": ["Sangam literature", "The Vedas", "Upanishads", "Puranas"], "answer": 0, "explanation": "They were sharply critical of the Buddhists and Jainas and preached ardent love of Shiva or Vishnu as the path to salvation. They drew upon the ideals of love and heroism as found in the Sangam literature..."},
    {"question": "There were how many Nayanars in total?", "options": ["63", "12", "108", "50"], "answer": 0, "explanation": "There were 63 Nayanars, who belonged to different caste backgrounds such as potters, 'untouchable' workers, peasants, hunters, soldiers, Brahmanas and chiefs."},
    {"question": "How many Alvars were there?", "options": ["12", "63", "24", "10"], "answer": 0, "explanation": "There were 12 Alvars, who came from equally divergent backgrounds, the best known being Periyalvar, his daughter Andal, Tondaradippodi Alvar and Nammalvar."},
    {"question": "Their songs are compiled in the Divya Prabandham. Whose songs does this refer to?", "options": ["The Alvars", "The Nayanars", "The Sufis", "The Buddhists"], "answer": 0, "explanation": "Their (Alvars') songs were compiled in the Divya Prabandham."},
    {"question": "Between the tenth and twelfth centuries, Chola and Pandya kings built elaborate temples around many of the shrines visited by the saint-poets, strengthening the links between:", "options": ["The bhakti tradition and temple worship", "Islam and Hinduism", "Kings and merchants", "Tribals and settled communities"], "answer": 0, "explanation": "Between the tenth and twelfth centuries Chola and Pandya kings built elaborate temples around many of the shrines visited by the saint-poets, strengthening the links between the bhakti tradition and temple worship."},
    {"question": "Who was Ramanuja?", "options": ["A twelfth-century Bhakti saint born in Tamil Nadu, deeply influenced by the Alvars", "A Sufi master", "A Chera king", "A Buddhist monk"], "answer": 0, "explanation": "Ramanuja, born in Tamil Nadu in the eleventh century, was deeply influenced by the Alvars. According to him the best means of attaining salvation was through intense devotion to Vishnu."},
    {"question": "What is the doctrine of Vishishtadvaita (qualified oneness), propounded by Ramanuja?", "options": ["The soul even when united with the Supreme God remained distinct", "There is only one God without any attributes", "The soul disappears upon salvation", "The universe is an illusion"], "answer": 0, "explanation": "He propounded the doctrine of Vishishtadvaita or qualified oneness in that the soul even when united with the Supreme God remained distinct."},
    {"question": "Who initiated the Virashaiva movement in Karnataka in the mid-twelfth century?", "options": ["Basavanna and his companions like Allama Prabhu and Akkamahadevi", "Shankara", "Ramanuja", "Namdev and Tukaram"], "answer": 0, "explanation": "The connection between the Tamil bhakti movement and temple worship... led to a reaction that is best represented in the Virashaiva movement initiated by Basavanna and his companions like Allama Prabhu and Akkamahadevi."},
    {"question": "What did the Virashaivas strongly argue for?", "options": ["The equality of all human beings and against Brahmanical ideas about caste and the treatment of women", "The strict observance of the caste system", "The construction of more temples", "Performing complex sacrifices"], "answer": 0, "explanation": "The Virashaivas argued strongly for the equality of all human beings and against Brahmanical ideas about caste and the treatment of women. They were also against all forms of ritual and idol worship."},
    {"question": "Who were the notable saint-poets of Maharashtra from the thirteenth to the seventeenth centuries?", "options": ["Jnaneshwar, Namdev, Eknath and Tukaram as well as women like Sakhubai", "Kabir and Raidas", "Sankaradeva and Chaitanyadeva", "Surdas and Tulsidas"], "answer": 0, "explanation": "From the thirteenth to the seventeenth centuries Maharashtra saw a great number of saint-poets... The most important among them were Jnaneshwar, Namdev, Eknath and Tukaram as well as women like Sakhubai, and the family of Chokhamela, who belonged to the 'untouchable' Mahar caste."},
    {"question": "The saint-poets of Maharashtra rejected:", "options": ["All forms of ritualism, outward display of piety and social differences based on birth", "The reading of the Bhagavad Gita", "Singing devotional songs", "Living with their families"], "answer": 0, "explanation": "These saint-poets rejected all forms of ritualism, outward display of piety and social differences based on birth. In fact they even rejected the idea of renunciation and preferred to live with their families..."},
    {"question": "What was the view of the Nathpanthis, Siddhacharas and Yogis regarding salvation?", "options": ["It lay in meditation on the formless Ultimate Reality", "It lay in bathing in the Ganges", "It lay in giving wealth to priests", "It lay in fighting for the king"], "answer": 0, "explanation": "To them the path to salvation lay in meditation on the formless Ultimate Reality and the realisation of oneness with it. To achieve this they advocated intense training of the mind and body through practices like yogasanas, breathing exercises and meditation."},
    {"question": "Sufis were Muslim mystics who rejected:", "options": ["Outward religiosity and emphasised love and devotion to God and compassion towards all fellow human beings", "The teachings of the Quran", "Fasting and prayer", "The existence of God"], "answer": 0, "explanation": "The Sufis were Muslim mystics. They rejected outward religiosity and emphasised love and devotion to God and compassion towards all fellow human beings."},
    {"question": "Islam propagated strict monotheism, meaning:", "options": ["Submission to one God", "Worship of multiple deities", "Rejection of all gods", "God taking human forms"], "answer": 0, "explanation": "Islam propagated strict monotheism or submission to one God."},
    {"question": "What is a 'silsila' in the context of Sufism?", "options": ["A spiritual genealogy or lineage of Sufi teachers", "A type of mosque", "A religious text", "A form of musical instrument"], "answer": 0, "explanation": "Among them were the Chishti silsila, which was among the most influential orders. It had a long line of teachers... silsila means a spiritual genealogy of Sufi teachers."},
    {"question": "Which Sufi order was among the most influential and had a long line of teachers like Khwaja Muinuddin of Ajmer and Qutbuddin Bakhtiyar Kaki of Delhi?", "options": ["Chishti silsila", "Suhrawardi silsila", "Qadiri silsila", "Naqshbandi silsila"], "answer": 0, "explanation": "The Chishti silsila was among the most influential orders. It had a long line of teachers like Khwaja Muinuddin Chishti of Ajmer, Qutbuddin Bakhtiyar Kaki of Delhi, Baba Farid of Punjab, Khwaja Nizamuddin Auliya of Delhi..."},
    {"question": "What is a 'khanqah' or hospice?", "options": ["A resting place for travellers and a place where Sufi masters held their assemblies", "A specialized market", "A royal palace", "A military barracks"], "answer": 0, "explanation": "The Sufi masters held their assemblies in their khanqahs or hospices. Devotees of all descriptions including members of the royalty and nobility, and ordinary people flocked to these khanqahs."}
];

global.cbseData["7"].history.mcqs.ch7 = ch7;
global.cbseData["7"].history.mcqs.ch8 = ch8;

let finalContent = 'const cbseData = ' + JSON.stringify(global.cbseData, null, 4) + ';\n';
fs.writeFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', finalContent);
console.log('Class 7 History Ch7 & Ch8 added.');
