const fs = require('fs');
let content = fs.readFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', 'utf8');
let evalContent = content.replace('const cbseData =', 'global.cbseData =');
eval(evalContent);

const ch9 = [
    {"question": "The Chera kingdom of Mahodayapuram was established in the ninth century in the south-western part of the peninsula, part of present-day:", "options": ["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh"], "answer": 0, "explanation": "The Chera kingdom of Mahodayapuram was established in the ninth century in the south-western part of the peninsula, part of present-day Kerala."},
    {"question": "Which language was likely spoken in the Chera kingdom of Mahodayapuram?", "options": ["Malayalam", "Tamil", "Kannada", "Telugu"], "answer": 0, "explanation": "It is likely that Malayalam was spoken in this area. The rulers introduced the Malayalam language and script in their inscriptions."},
    {"question": "The rulers of the Chera kingdom drew upon Sanskritic traditions. What 14th-century text deals with grammar and poetics in a style called Manipravalam?", "options": ["Lilatilakam", "Silappadikaram", "Manimekalai", "Tolkappiyam"], "answer": 0, "explanation": "A fourteenth-century text, the Lilatilakam, dealing with grammar and poetics, was composed in Manipravalam - literally, 'diamonds and corals' referring to the two languages, Sanskrit and the regional language."},
    {"question": "What is the cult of Jagannatha at Puri (Odisha) closely associated with?", "options": ["Vishnu", "Shiva", "Brahma", "Indra"], "answer": 0, "explanation": "In other regions, regional cultures grew around religious traditions. The best example of this process is the cult of Jagannatha (literally, lord of the world, a name for Vishnu) at Puri, Odisha."},
    {"question": "Who decided to erect a temple for Purushottama Jagannatha at Puri in the 12th century?", "options": ["Anantavarman, a ruler of the Ganga dynasty", "Rajaraja Chola", "Harsha", "Chandragupta Maurya"], "answer": 0, "explanation": "In the twelfth century, one of the most important rulers of the Ganga dynasty, Anantavarman, decided to erect a temple for Purushottama Jagannatha at Puri."},
    {"question": "What happened to the Jagannatha temple at Puri as it gained importance as a centre of pilgrimage?", "options": ["Its authority in social and political matters also increased", "It was destroyed by local people", "It lost all its wealth", "Pilgrims stopped visiting it"], "answer": 0, "explanation": "As the temple gained in importance as a centre of pilgrimage, its authority in social and political matters also increased. All those who conquered Odisha... attempted to gain control over the temple."},
    {"question": "In the 19th century, the region that constitutes most of present-day Rajasthan was called:", "options": ["Rajputana", "Marwar", "Mewar", "Gujarat"], "answer": 0, "explanation": "In the nineteenth century, the region that constitutes most of present-day Rajasthan was called Rajputana by the British."},
    {"question": "Rajput rulers liked to be perceived as:", "options": ["Valiant heroes who fought for their honour and chose death on the battlefield rather than face defeat", "Peacemakers who avoided all conflict", "Wealthy merchants", "Religious ascetics"], "answer": 0, "explanation": "This group (Rajputs) is associated with the idea of a hero... rulers cherished the ideal of the hero who fought valiantly, often choosing death on the battlefield rather than face defeat."},
    {"question": "How did stories about Rajput heroes spread?", "options": ["They were recorded in poems and songs, which were recited by specially trained minstrels", "They were carved on stone pillars", "They were painted on cave walls", "They were written in daily newspapers"], "answer": 0, "explanation": "Stories about Rajput heroes were recorded in poems and songs, which were recited by specially trained minstrels."},
    {"question": "Who was Kathak originally associated with?", "options": ["A caste of story-tellers in temples of north India", "Royal warriors of Rajasthan", "Priests in Kerala", "Weavers in Bengal"], "answer": 0, "explanation": "The term kathak is derived from katha, a word used in Sanskrit and other languages for story. The kathaks were originally a caste of story-tellers in temples of north India, who beautified their performances with gestures and songs."},
    {"question": "Which Mughal emperors patronized Kathak, allowing it to develop distinct features?", "options": ["Akbar, Jahangir and Shah Jahan", "Aurangzeb alone", "Babur and Humayun", "Only Bahadur Shah Zafar"], "answer": 0, "explanation": "Under the Mughal emperors and their nobles, Kathak was performed in the court, where it acquired its present features and developed into a form of dance with a distinctive style."},
    {"question": "Under whose patronage did Kathak grow into a major art form in the 19th century in Awadh?", "options": ["Wajid Ali Shah", "Siraj ud-Daulah", "Murshid Quli Khan", "Asaf-ud-Daula"], "answer": 0, "explanation": "Under the patronage of Wajid Ali Shah, the last Nawab of Awadh, it grew into a major art form."},
    {"question": "Which of the following is an accepted 'classical' dance style of India?", "options": ["Bharatanatyam (Tamil Nadu)", "Kathakali (Kerala)", "Odissi (Odisha)", "All of the above"], "answer": 3, "explanation": "Other dance forms that are recognised as classical at present are: Bharatanatyam (Tamil Nadu), Kathakali (Kerala), Odissi (Odisha), Kuchipudi (Andhra Pradesh), Manipuri (Manipur) and Kathak (North India)."},
    {"question": "Miniatures are generally:", "options": ["Small-sized paintings, generally done in water colour on cloth or paper", "Large wall murals", "Statues made of bronze", "Carvings on wooden doors"], "answer": 0, "explanation": "Miniatures (as their very name suggests) are small-sized paintings, generally done in water colour on cloth or paper."},
    {"question": "Which Himalayan foothills region developed a bold and intense style of miniature painting called Basohli?", "options": ["The region around modern-day Himachal Pradesh", "Kashmir", "Nepal", "Sikkim"], "answer": 0, "explanation": "By the late seventeenth century this region (around the modern-day state of Himachal Pradesh) had developed a bold and intense style of miniature painting called Basohli."},
    {"question": "The Kangra style of miniature painting was inspired by:", "options": ["The Vaishnavite traditions", "Shaivite traditions", "Islamic traditions", "Buddhist traditions"], "answer": 0, "explanation": "The Kangra artists by the mid-eighteenth century developed a style... The source of inspiration was the Vaishnavite traditions. Soft colours including cool blues and greens, and a lyrical treatment of themes distinguished Kangra painting."},
    {"question": "Bengali is derived from which ancient language?", "options": ["Sanskrit", "Prakrit", "Persian", "Arabic"], "answer": 0, "explanation": "It is generally assumed that Bengali is derived from Sanskrit. However, from the fourth-third centuries BCE, commercial ties began to develop between Bengal and Magadha (South Bihar), which may have led to the growing influence of Sanskrit."},
    {"question": "The early Bengali literature is divided into two categories. One is independent of Sanskrit, and the other is:", "options": ["Indebted to Sanskrit", "Indebted to Arabic", "Indebted to Persian", "Independent of all languages"], "answer": 0, "explanation": "Early Bengali literature may be divided into two categories - one indebted to Sanskrit and the other independent of it. The first includes translations of the Sanskrit epics... The second includes Nath literature..."},
    {"question": "Who were 'pirs' in Bengal?", "options": ["Community leaders who functioned as teachers and adjudicators, sometimes ascribed with supernatural powers", "Only kings", "Wealthy merchants", "Tax collectors"], "answer": 0, "explanation": "The early settlers in eastern Bengal sought some order... this was provided by community leaders, who also functioned as teachers and adjudicators and were sometimes ascribed with supernatural powers. People referred to them with affection and respect as pirs."},
    {"question": "The term 'pir' often included:", "options": ["Saints or Sufis", "Prominent religious personalities", "Deified soldiers and various Hindu and Buddhist deities", "All of the above"], "answer": 3, "explanation": "The term pir included saints or Sufis and other religious personalities, daring colonisers and deified soldiers, various Hindu and Buddhist deities and even animistic spirits."},
    {"question": "In Bengal, what type of architecture became very popular and reflected local culture?", "options": ["Mosques and temples built with a 'docala' or 'chauchala' roof", "Gigantic stone pyramids", "Castles with moats", "Tall minarets only"], "answer": 0, "explanation": "Many of the modest brick and terracotta temples in Bengal were built... Typical Bengali style had a double-roof (docala) or four-roof (chauchala)."},
    {"question": "The 'dochala' or 'chauchala' roofs in Bengal architecture were mainly constructed using:", "options": ["Mud and terracotta bricks", "Pure white marble", "Iron beams", "Glass panels"], "answer": 0, "explanation": "Many of the modest brick and terracotta temples in Bengal were built with the support of several 'low' social groups. These temples often adopted the docala or chauchala roof style."},
    {"question": "Mangalakavyas were:", "options": ["Auspicious poems dealing with local deities", "Laws regarding trade", "Songs about war only", "Biographies of kings"], "answer": 0, "explanation": "Mangalakavyas (literally auspicious poems, dealing with local deities) were part of early Bengali literature indebted to Sanskrit."},
    {"question": "Brahmanas in Bengal were permitted to eat what, distinguishing them from Brahmanas in some other regions?", "options": ["Fish", "Beef", "Chicken", "Pork"], "answer": 0, "explanation": "The Brihaddharma Purana, a thirteenth-century Sanskrit text from Bengal, permitted the local Brahmanas to eat certain varieties of fish, as fish was a traditional food in the riverine plains of Bengal."},
    {"question": "Fish and rice were the staple food in the riverine plains of Bengal. This is also reflected in the:", "options": ["Terracotta plaques on the walls of temples and viharas depicting scenes of fish being dressed", "Coins minted by the kings", "Weapons used by soldiers", "Clothing worn by nobles"], "answer": 0, "explanation": "Terracotta plaques on the walls of temples and viharas (Buddhist monasteries) depict scenes of fish being dressed and taken to the market in baskets."}
];

const ch10 = [
    {"question": "By the mid-eighteenth century, the political boundary of the Mughal Empire was drastically reshaped by the emergence of:", "options": ["Independent kingdoms", "The British East India Company", "The Marathas", "All of the above"], "answer": 3, "explanation": "If you look at the maps, you will see that the boundaries of the Mughal Empire were reshaped by the emergence of a number of independent kingdoms. By 1765, another power, the British, had successfully grabbed major chunks of territory in eastern India."},
    {"question": "Which Mughal Emperor fought a long war in the Deccan that depleted the military and financial resources of his empire?", "options": ["Aurangzeb", "Akbar", "Jahangir", "Shah Jahan"], "answer": 0, "explanation": "Emperor Aurangzeb had depleted the military and financial resources of his empire by fighting a long war in the Deccan."},
    {"question": "Under the later Mughals, the efficiency of the imperial administration broke down. Who became increasingly difficult for the emperors to control?", "options": ["Their powerful mansabdars and nobles appointed as governors (subadars)", "Peasants", "The East India Company", "Artisans"], "answer": 0, "explanation": "Under his successors, the efficiency of the imperial administration broke down. It became increasingly difficult for the later Mughal emperors to keep a check on their powerful mansabdars... Nobles appointed as governors (subadars) often controlled the offices of revenue and military administration (diwani and faujdari)."},
    {"question": "In 1739, who sacked and plundered the city of Delhi, taking away immense amounts of wealth?", "options": ["Nadir Shah, the ruler of Iran", "Ahmad Shah Abdali", "Shivaji", "Baji Rao I"], "answer": 0, "explanation": "In 1739, Nadir Shah, the ruler of Iran, sacked and plundered the city of Delhi and took away immense amounts of wealth."},
    {"question": "Following Nadir Shah's invasion, who invaded north India five times between 1748 and 1761?", "options": ["Ahmad Shah Abdali", "Genghis Khan", "Timur", "Babur"], "answer": 0, "explanation": "This invasion was followed by a series of plundering raids by the Afghan ruler Ahmad Shah Abdali, who invaded north India five times between 1748 and 1761."},
    {"question": "Awadh, Bengal and Hyderabad were the most important states to emerge from the decline of the Mughal Empire. Who founded the state of Awadh?", "options": ["Burhan-ul-Mulk Sa‘adat Khan", "Murshid Quli Khan", "Asaf Jah", "Alivardi Khan"], "answer": 0, "explanation": "Burhan-ul-Mulk Sa'adat Khan was appointed subadar of Awadh in 1722 and founded a state which was one of the most important to emerge out of the break-up of the Mughal Empire."},
    {"question": "Who was the founder of the state of Hyderabad?", "options": ["Nizam-ul-Mulk Asaf Jah", "Sa'adat Khan", "Murshid Quli Khan", "Safdar Jung"], "answer": 0, "explanation": "Nizam-ul-Mulk Asaf Jah, the founder of Hyderabad state, was one of the most powerful members at the court of the Mughal Emperor Farrukh Siyar."},
    {"question": "To reduce Mughal influence in Bengal, Murshid Quli Khan transferred all Mughal jagirdars to:", "options": ["Orissa", "Delhi", "Punjab", "Gujarat"], "answer": 0, "explanation": "Like the rulers of Hyderabad and Awadh, he also commanded the revenue administration of the state. In an effort to reduce Mughal influence in Bengal he transferred all Mughal jagirdars to Orissa and ordered a major reassessment of the revenues of Bengal."},
    {"question": "In the new states of Awadh, Bengal, and Hyderabad, revenue was often collected by contracting with:", "options": ["Revenue farmers (ijaradars)", "Only Mughal officers", "Foreign merchants", "Military commanders only"], "answer": 0, "explanation": "They contracted with revenue farmers for the collection of revenue. The practice of ijaradari... gradually spread all over India..."},
    {"question": "The state of Awadh depended on local bankers and 'mahajans' for loans. What right was given to the highest bidders in the revenue system?", "options": ["The right to collect the tax (ijara system)", "The right to rule the province", "The right to mint coins", "The right to maintain a personal army"], "answer": 0, "explanation": "The state sold the right to collect tax to the highest bidders. These 'revenue farmers' (ijaradars) agreed to pay the state a fixed sum of money."},
    {"question": "Many Rajput kings, particularly those of Amber and Jodhpur, had served the Mughals well. In exchange, they were permitted to enjoy considerable autonomy in their:", "options": ["Watan jagirs", "Subas", "Iqtas", "Khalsa lands"], "answer": 0, "explanation": "Many Rajput kings, particularly those of Amber and Jodhpur, had served under the Mughals with distinction. In exchange, they were permitted to enjoy considerable autonomy in their watan jagirs."},
    {"question": "Who founded the new capital at Jaipur and was given the subadari of Agra in 1722?", "options": ["Sawai Raja Jai Singh of Amber", "Raja Ajit Singh of Jodhpur", "Maharana Pratap", "Banda Bahadur"], "answer": 0, "explanation": "Sawai Raja Jai Singh of Amber was governor of Malwa... He founded his new capital at Jaipur and was given the subadari of Agra in 1722."},
    {"question": "Guru Gobind Singh fought several battles against the Rajput and Mughal rulers. What was the organization of the Sikhs called, instituted in 1699?", "options": ["The Khalsa", "The Dal Khalsa", "The Misls", "The Rakhi"], "answer": 0, "explanation": "After the institution of the Khalsa in 1699, the community got organized... Guru Gobind Singh had inspired the Khalsa with the belief that their destiny was to rule (raj karega khalsa)."},
    {"question": "Under whose leadership did the Sikhs rise in revolt after Guru Gobind Singh's death?", "options": ["Banda Bahadur", "Ranjit Singh", "Kapur Singh", "Jassa Singh Ahluwalia"], "answer": 0, "explanation": "After his death in 1708, the Khalsa rose in revolt against the Mughal authority under Banda Bahadur's leadership, declared their sovereign rule by striking coins..."},
    {"question": "In the eighteenth century, the Sikhs organized themselves into a number of bands called jathas, and later:", "options": ["Misls", "Dal Khalsa", "Sardars", "Rakhi"], "answer": 0, "explanation": "In the eighteenth century, the Sikhs organized themselves into a number of bands called jathas, and later misls."},
    {"question": "The grand army of the Sikhs (the combined forces of all misls) used to meet at Amritsar at the time of Baisakhi and Diwali to:", "options": ["Take collective decisions known as 'resolutions of the Guru' (gurmatas)", "Appoint a new Guru", "Surrender to the Mughals", "Count their wealth"], "answer": 0, "explanation": "The combined forces were known as the grand army (dal khalsa). The entire body used to meet at Amritsar at the time of Baisakhi and Diwali to take collective decisions known as 'resolutions of the Guru (gurmatas)'."},
    {"question": "What was the 'rakhi' system introduced by the Sikhs?", "options": ["A system offering protection to cultivators on the payment of a tax of 20 per cent of the produce", "A tying of thread between brothers and sisters", "A tax on trade", "A military training program"], "answer": 0, "explanation": "A system called rakhi was introduced, offering protection to cultivators on the payment of a tax of 20 per cent of the produce."},
    {"question": "Who reunited the Sikh groups and established his capital at Lahore in 1799?", "options": ["Maharaja Ranjit Singh", "Banda Bahadur", "Guru Gobind Singh", "Ahmad Shah Abdali"], "answer": 0, "explanation": "Maharaja Ranjit Singh reunited these groups and established his capital at Lahore in 1799."},
    {"question": "Who carved out a stable Maratha kingdom with the support of powerful warrior families (deshmukhs)?", "options": ["Shivaji", "Baji Rao I", "Balaji Vishwanath", "Sambhaji"], "answer": 0, "explanation": "Shivaji (1627-1680) carved out a stable kingdom with the support of powerful warrior families (deshmukhs). Groups of highly mobile, peasant-pastoralists (kunbis) provided the backbone of the Maratha army."},
    {"question": "After Shivaji's death, effective power in the Maratha state was wielded by a family of Chitpavan Brahmanas who served Shivaji's successors as:", "options": ["Peshwa (or principal minister)", "Subadar", "Faujdar", "Deshmukh"], "answer": 0, "explanation": "After Shivaji's death, effective power in the Maratha state was wielded by a family of Chitpavan Brahmanas who served Shivaji's successors as Peshwa (or principal minister). Poona became the capital of the Maratha kingdom."},
    {"question": "What was 'Chauth' in the Maratha revenue system?", "options": ["25 per cent of the land revenue claimed by zamindars, which the Marathas collected in the Deccan", "A tax of 9-10 percent of land revenue", "A tax on marriage", "A toll tax for travelers"], "answer": 0, "explanation": "Chauth was 25 per cent of the land revenue claimed by zamindars. In the Deccan this was collected by the Marathas."},
    {"question": "What was 'Sardeshmukhi'?", "options": ["9-10 per cent of the land revenue paid to the head revenue collector in the Deccan by the Marathas", "25 per cent of the land revenue", "A tax on trade", "A payment to the Peshwa"], "answer": 0, "explanation": "Sardeshmukhi was 9-10 per cent of the land revenue paid to the head revenue collector in the Deccan."},
    {"question": "The Maratha empire was not just militaristic; they developed an effective administrative system. Their revenue demands were:", "options": ["Adapted to local conditions and agricultural improvements", "Looted without any system", "Fixed centrally across all of India", "Never collected from peasants"], "answer": 0, "explanation": "Once conquest had been completed and Maratha rule was secure, revenue demands were gradually introduced taking local conditions into account."},
    {"question": "Who were the Jats?", "options": ["Prosperous agriculturists who consolidated their power around Delhi and Agra", "A nomadic trading tribe associated with Banjaras", "A group of Persian nobles", "Tribals of Gondwana"], "answer": 0, "explanation": "Like the other states the Jats consolidated their power during the late seventeenth and eighteenth-centuries. Under their leader, Churaman, they acquired control over territories situated to the west of the city of Delhi... The Jats were prosperous agriculturists..."},
    {"question": "Under whose leadership did the kingdom of Bharatpur emerge as a strong Jat state?", "options": ["Suraj Mal", "Churaman", "Badan Singh", "Jawahir Shah"], "answer": 0, "explanation": "Under Suraj Mal the kingdom of Bharatpur emerged as a strong state. When Nadir Shah sacked Delhi in 1739, many of the city's notables took refuge there."}
];

global.cbseData["7"].history.mcqs.ch9 = ch9;
global.cbseData["7"].history.mcqs.ch10 = ch10;

let finalContent = 'const cbseData = ' + JSON.stringify(global.cbseData, null, 4) + ';\n';
fs.writeFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', finalContent);
console.log('Class 7 History Ch9 & Ch10 added.');
