const fs = require('fs');
let content = fs.readFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', 'utf8');
let evalContent = content.replace('const cbseData =', 'global.cbseData =');
eval(evalContent);

const ch1 = [
    {"question": "Who was al-Idrisi?", "options": ["An Arab geographer", "A French cartographer", "A Persian poet", "An Indian king"], "answer": 0, "explanation": "Al-Idrisi was an Arab geographer who made a world map in 1154 CE."},
    {"question": "What is cartography?", "options": ["The study of stars", "The science of making maps", "The study of old manuscripts", "The study of coins"], "answer": 1, "explanation": "Cartography is the science or practice of drawing maps."},
    {"question": "Which language was not a part of the medieval period in India?", "options": ["Persian", "Arabic", "Sanskrit", "English"], "answer": 3, "explanation": "English became prominent much later, whereas Persian, Arabic, and Sanskrit were used in the medieval period."},
    {"question": "In the Middle Ages, what did the term 'foreigner' (Pardesi) mean?", "options": ["Someone from a different country", "Any stranger who was not part of that society or culture", "A trader from Europe", "An invader"], "answer": 1, "explanation": "In the medieval period, a 'foreigner' was any stranger who was not a part of a particular society or village."},
    {"question": "Who used the term 'Hindustan' in the thirteenth century?", "options": ["Babur", "Minhaj-i-Siraj", "Amir Khusrau", "Al-Idrisi"], "answer": 1, "explanation": "Minhaj-i-Siraj, a chronicler who wrote in Persian, used the term 'Hindustan' in the thirteenth century."},
    {"question": "To Minhaj-i-Siraj, 'Hindustan' meant:", "options": ["The entire Indian subcontinent", "The areas of Punjab, Haryana, and the lands between the Ganga and Yamuna", "South India only", "The lands ruled by the Mughals"], "answer": 1, "explanation": "Minhaj-i-Siraj meant the areas of Punjab, Haryana, and the lands between the Ganga and Yamuna."},
    {"question": "Which new technology was introduced in weaving during this period?", "options": ["Persian wheel", "Spinning wheel", "Power loom", "Flying shuttle"], "answer": 1, "explanation": "The spinning wheel was introduced in weaving during the medieval period."},
    {"question": "Which of these crops were introduced into the subcontinent during the medieval period?", "options": ["Potatoes, corn, chillies, tea and coffee", "Wheat, barley, rice", "Cotton, jute, indigo", "Mangoes, bananas, coconuts"], "answer": 0, "explanation": "Potatoes, corn, chillies, tea, and coffee were introduced during this period."},
    {"question": "Archives are places where:", "options": ["Kings lived", "Bulls were worshipped", "Documents and manuscripts are stored", "Grains are stored"], "answer": 2, "explanation": "Archives are places where historical documents and manuscripts are stored."},
    {"question": "Who copied manuscripts by hand before the invention of the printing press?", "options": ["Scribes", "Cartographers", "Artisans", "Peasants"], "answer": 0, "explanation": "Scribes were people who copied manuscripts by hand."},
    {"question": "What is a 'Jati Panchayat'?", "options": ["A council of elders regulating the affairs of a jati", "The king's court", "A market committee", "A group of religious leaders"], "answer": 0, "explanation": "Jati Panchayats were councils or assemblies of elders that enforced regulations among the members of their jati."},
    {"question": "Which group of people became politically important during the medieval period?", "options": ["Rajputs", "Mauryas", "Guptas", "Harappans"], "answer": 0, "explanation": "The Rajputs became an important and powerful group of people during the medieval period."},
    {"question": "Ziyauddin Barani was a fourteenth-century:", "options": ["Geographer", "Chronicler", "Poet", "King"], "answer": 1, "explanation": "Ziyauddin Barani was a fourteenth-century chronicler."},
    {"question": "Who was the fourteenth-century poet who used the word 'Hind'?", "options": ["Babur", "Akbar", "Amir Khusrau", "Minhaj-i-Siraj"], "answer": 2, "explanation": "The poet Amir Khusrau used the word 'Hind' in the fourteenth century."},
    {"question": "Which new technology was used in irrigation during this period?", "options": ["Tubewells", "Persian wheel", "Canal locking", "Drip irrigation"], "answer": 1, "explanation": "The Persian wheel was introduced in irrigation during the medieval period."},
    {"question": "Who were considered 'Rajputs'?", "options": ["Sons of rulers", "A group claiming Kshatriya caste status", "Soldiers and commanders", "All of the above"], "answer": 3, "explanation": "Rajput means 'son of a ruler'. Later, the term included soldiers, commanders, and those claiming Kshatriya caste status."},
    {"question": "Habitat refers to:", "options": ["Environment of a region and the social and economic lifestyle of its residents", "A special tax", "A type of ancient house", "A weapon"], "answer": 0, "explanation": "Habitat refers to the environment of a region and the social and economic lifestyle of its residents."},
    {"question": "What led to the migration of forest-dwellers?", "options": ["Wars", "Gradual clearing of forests and extension of agriculture", "Floods", "earthquakes"], "answer": 1, "explanation": "The gradual clearing of forests and the extension of agriculture forced many forest-dwellers to migrate."},
    {"question": "Brahmanas earned a lot of respect in society mainly because of:", "options": ["Their wealth", "Their knowledge of Sanskrit texts", "Their military skills", "Their trade networks"], "answer": 1, "explanation": "The Brahmanas' knowledge of Sanskrit texts earned them a lot of respect in society."},
    {"question": "Patrons in the medieval period were usually:", "options": ["Poor farmers", "Wealthy merchants", "Powerful and wealthy individuals who supported artists, craftspersons, or learned men", "Slaves"], "answer": 2, "explanation": "Patrons were influential, wealthy individuals who supported another person - an artiste, a craftsperson, a learned man, or a noble."},
    {"question": "Which two major religions saw significant developments during this period?", "options": ["Hinduism and Islam", "Buddhism and Jainism", "Christianity and Judaism", "Sikhism and Zoroastrianism"], "answer": 0, "explanation": "Important changes occurred in Hinduism and Islam during the medieval period."},
    {"question": "The idea of bhakti refers to:", "options": ["Blind faith in a king", "Performing complex sacrifices", "A loving, personal devotion to a deity without the aid of priests", "Worshipping nature"], "answer": 2, "explanation": "Bhakti was the idea of a loving, personal deity that devotees could reach without the aid of priests or elaborate rituals."},
    {"question": "Historians divide the past into periods based on:", "options": ["Significant economic and social changes", "Changes in kings", "Changes in climate", "Changes in borders"], "answer": 0, "explanation": "Historians divide the past into large segments or periods depending on significant economic and social changes."},
    {"question": "In the middle ages, the term 'Shia' and 'Sunni' are associated with:", "options": ["Hinduism", "Islam", "Jainism", "Buddhism"], "answer": 1, "explanation": "Shia and Sunni are two major branches of Islam that emerged based on beliefs about the rightful leadership of the Muslim community."},
    {"question": "Which of these terms meant a 'city-dweller' in the past?", "options": ["Pardesi", "Ajnabi", "Nagarvasi", "Vanvasi"], "answer": 2, "explanation": "While 'foreigners' were pardesi or ajnabi, a city-dweller or native to the town was different."}
];

const ch2 = [
    {"question": "Who were the 'samantas'?", "options": ["Kings", "Big landlords or warrior chiefs in different regions", "Traders", "Priests"], "answer": 1, "explanation": "By the seventh century, there were big landlords or warrior chiefs in different regions whom kings acknowledged as their subordinates or samantas."},
    {"question": "What was the 'hiranya-garbha'?", "options": ["A golden bowl", "A ritual to be 'reborn' as a Kshatriya", "A type of tax", "A battle formation"], "answer": 1, "explanation": "Hiranya-garbha literally means the golden womb. When this ritual was performed with the help of Brahmanas, it was thought to lead to the 'rebirth' of the sacrificer as a Kshatriya."},
    {"question": "The Rashtrakutas were initially subordinate to the:", "options": ["Cholas", "Chalukyas of Karnataka", "Pallavas", "Palas"], "answer": 1, "explanation": "Initially, the Rashtrakutas in the Deccan were subordinate to the Chalukyas of Karnataka."},
    {"question": "Which Rashtrakuta chief overthrew his Chalukya overlord and performed the hiranya-garbha ritual?", "options": ["Dantidurga", "Krishna I", "Amoghavarsha", "Dhruva"], "answer": 0, "explanation": "In the mid-Eighth century, Dantidurga, a Rashtrakuta chief, overthrew his Chalukya overlord and performed the hiranya-garbha."},
    {"question": "Kadamba Mayurasharman and Gurjara-Pratihara Harichandra were originally:", "options": ["Kshatriyas", "Vaishyas", "Brahmanas", "Shudras"], "answer": 2, "explanation": "They were Brahmanas who gave up their traditional professions, took to arms, and successfully established kingdoms in Karnataka and Rajasthan respectively."},
    {"question": "The tripartite struggle in the medieval period was for the control over the city of:", "options": ["Kanauj", "Delhi", "Ujjain", "Pataliputra"], "answer": 0, "explanation": "Rulers belonging to the Gurjara-Pratihara, Rashtrakuta, and Pala dynasties fought for control over Kanauj. This was termed the 'tripartite struggle' by historians."},
    {"question": "What was 'vetti' in the Chola empire?", "options": ["A form of tax collected as forced labour", "A land grant", "A type of coin", "A religious ceremony"], "answer": 0, "explanation": "Vetti was a tax taken not in cash but in the form of forced labour by the Chola administration."},
    {"question": "Who invaded the Indian subcontinent from Afghanistan and raided the Somnath temple?", "options": ["Muhammad Ghori", "Sultan Mahmud of Ghazni", "Babur", "Nadir Shah"], "answer": 1, "explanation": "Sultan Mahmud of Ghazni from Afghanistan raided the subcontinent almost every year, and much of the wealth he looted was from wealthy temples like Somnath in Gujarat."},
    {"question": "Al-Biruni, a scholar entrusted by Mahmud of Ghazni, wrote an account of the subcontinent called:", "options": ["Tarikh-ul-Hind", "Kitab al-Hind", "Ain-i-Akbari", "Baburnama"], "answer": 1, "explanation": "Al-Biruni wrote the Kitab al-Hind, an important source for historians regarding the Indian subcontinent."},
    {"question": "Which ruler defeated the Afghan ruler Sultan Muhammad Ghori in 1191?", "options": ["Prithviraja III", "Rajaraja Chola", "Mahmud of Ghazni", "Dantidurga"], "answer": 0, "explanation": "Prithviraja III (1168-1192), a Chahamana ruler, defeated the Afghan ruler Sultan Muhammad Ghori in 1191."},
    {"question": "Which dynasty ruled the region around the Kaveri delta before the Cholas rose to power?", "options": ["Muttaraiyar", "Pallavas", "Pandyas", "Cheras"], "answer": 0, "explanation": "A minor chiefly family known as the Muttaraiyar held power in the Kaveri delta. They were subordinate to the Pallava kings of Kanchipuram."},
    {"question": "Who built the town of Thanjavur and a temple for goddess Nishumbhasudini?", "options": ["Rajaraja I", "Rajendra I", "Vijayalaya", "Dantidurga"], "answer": 2, "explanation": "Vijayalaya, belonging to the ancient chiefly family of the Cholas, captured the Kaveri delta and built the town of Thanjavur and a temple for goddess Nishumbhasudini."},
    {"question": "Who is considered the most powerful Chola ruler?", "options": ["Vijayalaya", "Aditya I", "Rajaraja I", "Parantaka I"], "answer": 2, "explanation": "Rajaraja I, who became king in 985, is considered the most powerful Chola ruler and expanded control over most areas."},
    {"question": "The magnificent temples of Thanjavur and Gangaikondacholapuram were built by:", "options": ["Rajaraja and Rajendra", "Vijayalaya and Aditya", "Ashoka and Bindusara", "Harsha and Pulakeshin"], "answer": 0, "explanation": "The big temples of Thanjavur and Gangaikondacholapuram, built by Rajaraja and Rajendra, are architectural and sculptural marvels."},
    {"question": "What is unique about Chola bronze images?", "options": ["They were mostly of rulers", "They are considered amongst the finest in the world", "They were very small", "They were plain without any decoration"], "answer": 1, "explanation": "Chola bronze images are considered amongst the finest in the world, often depicting deities but sometimes also devotees."},
    {"question": "Settlements of peasants during the Chola period were known as:", "options": ["Nadu", "Ur", "Sabha", "Grama"], "answer": 1, "explanation": "Settlements of peasants, known as ur, became prosperous with the spread of irrigation agriculture."},
    {"question": "What was 'nadu' in the Chola empire?", "options": ["A type of tax", "A group of villages", "A market town", "A temple chariot"], "answer": 1, "explanation": "Groups of villages (ur) formed larger units called nadu, which performed administrative functions including dispensing justice and collecting taxes."},
    {"question": "Which title was given to wealthy landowners by Chola kings as a mark of respect?", "options": ["Muvendavelan", "Samanta", "Raja", "Sultan"], "answer": 0, "explanation": "Titles like muvendavelan (a velan or peasant serving three kings) or araiyar (chief) were given as markers of respect."},
    {"question": "Land granted to Brahmanas was known as:", "options": ["Brahmadeya", "Devadana", "Vellanvagai", "Pallichchhandam"], "answer": 0, "explanation": "Brahmanas often received land grants or brahmadeya, leading to the emergence of numerous Brahmana settlements in the Kaveri valley."},
    {"question": "What is 'Vellanvagai'?", "options": ["Land of non-Brahmana peasant proprietors", "Land gifted to temples", "Land meant for the maintenance of a school", "Land donated to Jaina institutions"], "answer": 0, "explanation": "According to Chola inscriptions, Vellanvagai was the land of non-Brahmana peasant proprietors."},
    {"question": "What was 'Devadana' or 'Tirunamattukkani'?", "options": ["Land gifted to temples", "Land given to warriors", "Land for Brahmanas", "Land for Jaina institutions"], "answer": 0, "explanation": "Devadana or Tirunamattukkani refers to land gifted to temples."},
    {"question": "Associations of traders were known as:", "options": ["Nagarams", "Sabhas", "Samantas", "Ur"], "answer": 0, "explanation": "Associations of traders known as nagarams also occasionally performed administrative functions in towns."},
    {"question": "The details of how the sabha (assembly) was organized are provided in the inscriptions from:", "options": ["Uttaramerur", "Thanjavur", "Kanchipuram", "Madurai"], "answer": 0, "explanation": "Inscriptions from Uttaramerur in Chingleput district, Tamil Nadu, provide details of the way the sabha was organized into various committees."},
    {"question": "What was a pre-requisite for becoming a member of a sabha committee?", "options": ["Must own the land from which land revenue is collected", "Must be a woman", "Must not know the Vedas", "Must be a trader"], "answer": 0, "explanation": "Candidates must own land from which land revenue is collected, have their own homes, be between 35 and 70 years, and have knowledge of the Vedas."},
    {"question": "Who was the author of the long Sanskrit poem containing the history of kings who ruled over Kashmir?", "options": ["Kalhana", "Al-Biruni", "Amir Khusrau", "Banabhatta"], "answer": 0, "explanation": "A long Sanskrit poem detailing the history of Kashmir's kings was composed by an author named Kalhana, who used various sources to write his account."}
];

global.cbseData["7"].history.mcqs.ch1 = ch1;
global.cbseData["7"].history.mcqs.ch2 = ch2;

let finalContent = 'const cbseData = ' + JSON.stringify(global.cbseData, null, 4) + ';\n';
fs.writeFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', finalContent);
console.log('Class 7 History Ch1 & Ch2 added.');
