const fs = require('fs');
let content = fs.readFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', 'utf8');
let evalContent = content.replace('const cbseData =', 'global.cbseData =');
eval(evalContent);

const ch3 = [
    {"question": "Who first became the capital of a kingdom under the Tomara Rajputs?", "options": ["Delhi", "Agra", "Ajmer", "Kanauj"], "answer": 0, "explanation": "Delhi first became the capital of a kingdom under the Tomara Rajputs, who were defeated in the middle of the twelfth century by the Chauhans."},
    {"question": "The coins minted in Delhi, which had a wide circulation, were called:", "options": ["Delhiwal", "Tanka", "Rupiya", "Jital"], "answer": 0, "explanation": "Many rich Jaina merchants lived in the city and constructed several temples. Coins minted here, called dehliwal, had a wide circulation."},
    {"question": "What is 'Tarikh' (singular) or 'Tawarikh' (plural)?", "options": ["Histories written in Persian", "Types of coins", "Taxes on land", "Names of Sultanate capitals"], "answer": 0, "explanation": "Valuable histories, called tarikh (singular) or tawarikh (plural), were written in Persian, the language of administration under the Delhi Sultans."},
    {"question": "Who were the authors of 'tawarikh'?", "options": ["Peasants", "Learned men: secretaries, administrators, poets and courtiers", "Foreign travelers", "Slaves and military men"], "answer": 1, "explanation": "The authors of tawarikh were learned men: secretaries, administrators, poets and courtiers, who both recounted events and advised rulers on governance."},
    {"question": "The authors of tawarikh advised rulers on the need to preserve an 'ideal' social order based on:", "options": ["Democracy and equality", "Birthright and gender distinctions", "Wealth and property", "Education and skill"], "answer": 1, "explanation": "They advised rulers on the need to preserve an 'ideal' social order based on birthright and gender distinctions, which were not shared by everybody."},
    {"question": "In 1236, who became the Sultan of Delhi?", "options": ["Iltutmish", "Raziyya", "Balban", "Alauddin Khalji"], "answer": 1, "explanation": "In 1236, Sultan Iltutmish's daughter, Raziyya, became Sultan. The chronicler Minhaj-i Siraj recognized that she was more able and qualified than all her brothers."},
    {"question": "What is a 'garrison town'?", "options": ["A fortified settlement with soldiers", "A town famous for markets", "A religious center", "A temporary camp"], "answer": 0, "explanation": "A garrison town is a fortified settlement, with soldiers."},
    {"question": "What is a 'hinterland'?", "options": ["A fortified settlement", "The lands adjacent to a city or port that supply it with goods and services", "A special tax", "An administrative division"], "answer": 1, "explanation": "Hinterland describes the lands adjacent to a city or port that supply it with goods and services."},
    {"question": "Which ruler's campaigns along the 'internal frontier' aimed at consolidating the hinterlands of the garrison towns?", "options": ["Raziyya", "Qutbuddin Aybak", "Ghiyasuddin Balban", "Ibrahim Lodi"], "answer": 2, "explanation": "Campaigns along the 'internal frontier' of the Sultanate aimed at consolidating the hinterlands of the garrison towns, particularly during the reigns of Balban, Alauddin Khalji and Muhammad Tughluq."},
    {"question": "Who built the Quwwat al-Islam mosque?", "options": ["Qutbuddin Aybak", "Iltutmish", "Delhi Sultans together", "Alauddin Khalji"], "answer": 2, "explanation": "The Quwwat al-Islam mosque and minaret were built during the last decade of the twelfth century... The mosque was enlarged by Iltutmish and Alauddin Khalji."},
    {"question": "A 'masjid' is a place where:", "options": ["A Muslim prostrates in reverence to Allah", "Merchants meet", "Soldiers are trained", "The Sultan holds court"], "answer": 0, "explanation": "A mosque is called a masjid in Arabic, literally a place where a Muslim prostrates in reverence to Allah."},
    {"question": "The early Delhi Sultans, especially Iltutmish, favored their special slaves purchased for military service, called:", "options": ["Bandagan", "Iqtadars", "Samantas", "Amirs"], "answer": 0, "explanation": "Iltutmish favoured their special slaves purchased for military service, called bandagan in Persian. They were carefully trained to man some of the most important political offices in the kingdom."},
    {"question": "The Khaljis and Tughluqs appointed military commanders as governors of territories of varying sizes, which were called:", "options": ["Iqta", "Suba", "Khalisa", "Mandal"], "answer": 0, "explanation": "The Khaljis and Tughluqs continued to use bandagan and appointed military commanders as governors of territories of varying sizes. These lands were called iqta."},
    {"question": "The holder of an 'iqta' was called an:", "options": ["Iqtadar or muqti", "Amir", "Subadar", "Mansabdar"], "answer": 0, "explanation": "Their holder was called iqtadar or muqti."},
    {"question": "What was the duty of the muqtis?", "options": ["To lead military campaigns and maintain law and order in their iqtas", "To translate Persian texts", "To trade with foreign nations", "To mint coins"], "answer": 0, "explanation": "The duty of the muqtis was to lead military campaigns and maintain law and order in their iqtas."},
    {"question": "How did muqtis get paid?", "options": ["From the royal treasury in gold", "They extracted revenues of their assignments as salary", "They were not paid", "By capturing neighboring kingdoms"], "answer": 1, "explanation": "In exchange for their military services, the muqtis collected the revenues of their assignments as salary. They also paid their soldiers from these revenues."},
    {"question": "Under Alauddin Khalji, the state brought the assessment and collection of which tax under its own control?", "options": ["Kharaj (land revenue)", "Jizya", "Zakat", "Chauth"], "answer": 0, "explanation": "Under Alauddin Khalji, the state brought the assessment and collection of land revenue under its own control. The rights of the local chieftains to levy taxes were cancelled."},
    {"question": "Khraj, a tax on cultivation, amounted to about what percentage of the peasant's produce?", "options": ["10 per cent", "25 per cent", "50 per cent", "90 per cent"], "answer": 2, "explanation": "There were three types of taxes: (1) on cultivation called kharaj and amounting to about 50 per cent of the peasant's produce..."},
    {"question": "Who was the Mongol leader who invaded Transoxiana in north-east Iran in 1219?", "options": ["Timur", "Genghis Khan", "Kublai Khan", "Hulagu Khan"], "answer": 1, "explanation": "The Mongols under Genghis Khan invaded Transoxiana in north-east Iran in 1219 and the Delhi Sultanate faced their onslaught soon after."},
    {"question": "Which Sultan constructed a new garrison town named Siri for his soldiers?", "options": ["Iltutmish", "Alauddin Khalji", "Muhammad Tughluq", "Balban"], "answer": 1, "explanation": "Alauddin constructed a new garrison town named Siri for his soldiers."},
    {"question": "Instead of constructing a new garrison town, which Sultan emptied the oldest of the four cities of Delhi (Dehli-i Kuhna) and made it a soldier camp?", "options": ["Alauddin Khalji", "Muhammad Tughluq", "Firoz Shah Tughluq", "Sikandar Lodi"], "answer": 1, "explanation": "Rather than constructing a new garrison town, the oldest of the four cities of Delhi (Dehli-i Kuhna) was emptied of its residents and the soldiers garrisoned there."},
    {"question": "Where did Muhammad Tughluq force the residents of Dehli-i Kuhna to move?", "options": ["Agra", "Daulatabad", "Lahore", "Jaunpur"], "answer": 1, "explanation": "The residents of the old city were sent to the new capital of Daulatabad in the south."},
    {"question": "To pay the soldiers, Muhammad Tughluq used a 'token' currency, made out of:", "options": ["Gold and silver", "Cheap metals, not gold and silver", "Leather", "Paper"], "answer": 1, "explanation": "Muhammad Tughluq also paid his soldiers cash salaries but instead of controlling prices, he used a 'token' currency, made out of cheap metals, not gold and silver."},
    {"question": "Who succeeded the Tughluqs and ruled from Delhi and Agra until 1526?", "options": ["Sayyid and Lodi dynasties", "Mughals", "Rajputs", "Marathas"], "answer": 0, "explanation": "After the Tughluqs, the Sayyid and Lodi dynasties ruled from Delhi and Agra until 1526."},
    {"question": "Sher Shah Suri started his career as:", "options": ["A sultan in Delhi", "The manager of a small territory for his uncle in Bihar", "A general in the Mongol army", "A wealthy merchant"], "answer": 1, "explanation": "Sher Shah Suri (1540-1545) started his career as the manager of a small territory for his uncle in Bihar and eventually challenged and defeated the Mughal emperor Humayun."}
];

const ch4 = [
    {"question": "The Mughals were descendants of two great lineages of rulers. From their mother's side, they were descendants of:", "options": ["Timur", "Genghis Khan", "Alauddin Khalji", "Sher Shah Suri"], "answer": 1, "explanation": "From their mother's side, they were descendants of Genghis Khan (died 1227), ruler of the Mongol tribes, China and Central Asia."},
    {"question": "From their father's side, the Mughals were the successors of:", "options": ["Genghis Khan", "Timur", "Babur", "Iltutmish"], "answer": 1, "explanation": "From their father's side, they were the successors of Timur (died 1404), the ruler of Iran, Iraq and modern-day Turkey."},
    {"question": "Which ancestry did the Mughals prefer to be associated with?", "options": ["Mongol ancestry (Genghis Khan)", "Timurid ancestry", "Afghan ancestry", "Rajput ancestry"], "answer": 1, "explanation": "The Mughals did not like to be called Mughal or Mongol... On the other hand, the Mughals were proud of their Timurid ancestry, not least of all because their great ancestor had captured Delhi in 1398."},
    {"question": "Who was the first Mughal emperor?", "options": ["Humayun", "Akbar", "Babur", "Jahangir"], "answer": 2, "explanation": "Babur, the first Mughal emperor (1526-1530)."},
    {"question": "Babur defeated the Sultan of Delhi, Ibrahim Lodi, in 1526 at the battle of:", "options": ["Panipat", "Khanwa", "Chanderi", "Haldighati"], "answer": 0, "explanation": "In 1526 he defeated the Sultan of Delhi, Ibrahim Lodi, at Panipat and captured Delhi and Agra."},
    {"question": "Primogeniture refers to the rule of inheritance where:", "options": ["The eldest son inherits his father's estate", "The estate is divided equally amongst all sons", "The estate is inherited by the wife", "The youngest son inherits the estate"], "answer": 0, "explanation": "The Mughals did not believe in the rule of primogeniture, where the eldest son inherited his father's estate."},
    {"question": "Instead of primogeniture, the Mughals followed the custom of:", "options": ["Matrilineal descent", "Coparcenary inheritance", "Electoral monarchy", "Adoption"], "answer": 1, "explanation": "Instead they followed the Mughal and Timurid custom of coparcenary inheritance, or a division of the inheritance amongst all the sons."},
    {"question": "Those who joined Mughal service were enrolled as:", "options": ["Mansabdars", "Samantas", "Iqtadars", "Subadars"], "answer": 0, "explanation": "As the empire expanded to encompass different regions the Mughals recruited diverse bodies of people. Those who joined Mughal service were enrolled as mansabdars."},
    {"question": "The term 'mansabdar' refers to an individual who holds a 'mansab', meaning:", "options": ["A religious title", "A position or rank", "A type of land", "A tax exemption"], "answer": 1, "explanation": "The term mansabdar refers to an individual who holds a mansab, meaning a position or rank."},
    {"question": "What three things were determined by the mansabdari grading system?", "options": ["Rank, salary and military responsibilities", "Religion, caste and region", "Age, height and weight", "Tax, land and titles"], "answer": 0, "explanation": "It was a grading system used by the Mughals to fix (1) rank, (2) salary and (3) military responsibilities."},
    {"question": "Rank and salary in the mansabdari system were determined by a numerical value called:", "options": ["Zat", "Sawar", "Jagir", "Kharaj"], "answer": 0, "explanation": "Rank and salary were determined by a numerical value called zat. The higher the zat, the more prestigious was the noble's position in court and the larger his salary."},
    {"question": "Mansabdars received their salaries as revenue assignments called:", "options": ["Iqtas", "Jagirs", "Khalisa", "Inam"], "answer": 1, "explanation": "Mansabdars received their salaries as revenue assignments called jagirs which were somewhat like iqtas."},
    {"question": "Unlike muqtis, most mansabdars did not actually reside in or administer their:", "options": ["Capital", "Jagirs", "Palaces", "Forts"], "answer": 1, "explanation": "Unlike muqtis, most mansabdars did not actually reside in or administer their jagirs. They only had rights to the revenue of their assignments which was collected for them by their servants..."},
    {"question": "What was 'Zabt' in the Mughal empire?", "options": ["A strict religious law", "A revenue system based on a careful survey of crop yields and prices", "A punishment", "A type of army division"], "answer": 1, "explanation": "Each province was divided into revenue circles with its own schedule of revenue rates for individual crops. This revenue system was known as zabt."},
    {"question": "Who was Akbar's revenue minister who carried out the careful survey of crops, prices and areas?", "options": ["Birbal", "Todar Mal", "Abul Fazl", "Raja Man Singh"], "answer": 1, "explanation": "Akbar's revenue minister, Todar Mal, carried out a careful survey of crop yields, prices and areas cultivated for a 10-year period (1570-1580)."},
    {"question": "Who wrote 'Akbar Nama', the history of Akbar's reign?", "options": ["Todar Mal", "Faizi", "Abul Fazl", "Jahangir"], "answer": 2, "explanation": "Akbar ordered one of his close friends and courtiers, Abul Fazl, to write a history of his reign. Abul Fazl wrote a three-volume history of Akbar's reign, titled Akbar Nama."},
    {"question": "What is the third volume of the Akbar Nama called, which deals with Akbar's administration?", "options": ["Ain-i Akbari", "Tuzuk-i-Baburi", "Tarikh-i-Firoz Shahi", "Ibadat Khana"], "answer": 0, "explanation": "The third volume is the Ain-i Akbari. It deals with Akbar's administration, household, army, the revenues and the geography of his empire."},
    {"question": "Akbar divided his empire into provinces called:", "options": ["Subas", "Iqtas", "Sarkars", "Parganas"], "answer": 0, "explanation": "The empire was divided into provinces called subas, governed by a subadar..."},
    {"question": "The financial officer of a suba was known as the:", "options": ["Subadar", "Diwan", "Bakhshi", "Faujdar"], "answer": 1, "explanation": "For the maintenance of peace and order in his province, the subadar was supported by other officers such as the military paymaster (bakhshi), the minister in charge of religious and charitable patronage (sadr), military commanders (faujdars) and the town police commander (kotwal). The financial officer was the diwan."},
    {"question": "The discussions at the ibadat khana led Akbar to the idea of 'sulh-i kul' or:", "options": ["Universal peace", "Holy war", "Divine kingship", "Absolute power"], "answer": 0, "explanation": "This interaction with people of different faiths made Akbar realise that religious scholars who emphasised ritual and dogma were often bigots. Their teachings created divisions and disharmony amongst his subjects. This eventually led Akbar to the idea of sulh-i kul or 'universal peace'."},
    {"question": "Which emperor is well known for following Akbar's policy of 'sulh-i kul'?", "options": ["Jahangir and Shah Jahan", "Aurangzeb", "Babur", "Humayun"], "answer": 0, "explanation": "Abul Fazl helped Akbar in framing a vision of governance around this idea of sulh-i kul... This principle of governance was followed by Jahangir and Shah Jahan as well."},
    {"question": "During Shah Jahan's reign, the highest-ranking mansabdars were exceptionally:", "options": ["Large in number", "Small in number", "Rebellious", "Poor"], "answer": 1, "explanation": "In the 20th year of Shah Jahan's reign, the highest-ranking mansabdars were only 445 in number out of a total of 8,000."},
    {"question": "The word 'zamingdar' in the Mughal administration stood for:", "options": ["All intermediaries, whether local headmen or powerful chieftains", "Only the king", "Slaves", "Merchants"], "answer": 0, "explanation": "The Mughals used one term – zamindars – to describe all intermediaries, whether they were local headmen of villages or powerful chieftains."},
    {"question": "Which Mughal Emperor faced the Maratha campaigns led by Shivaji?", "options": ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"], "answer": 3, "explanation": "Aurangzeb insulted Shivaji who escaped from Agra, declared himself an independent king and resumed his campaigns against the Mughals."},
    {"question": "Who was Nur Jahan?", "options": ["Wife of Jahangir", "Wife of Akbar", "Daughter of Babur", "Mother of Shah Jahan"], "answer": 0, "explanation": "Mehrunnisa married the Emperor Jahangir in 1611 and received the title Nur Jahan."}
];

global.cbseData["7"].history.mcqs.ch3 = ch3;
global.cbseData["7"].history.mcqs.ch4 = ch4;

let finalContent = 'const cbseData = ' + JSON.stringify(global.cbseData, null, 4) + ';\n';
fs.writeFileSync('c:/Users/dell/Desktop/mcqs/js/data.js', finalContent);
console.log('Class 7 History Ch3 & Ch4 added.');
